version: '3.8'
services:
  backend:
    image: hotel-management-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
      - "5003:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=hotel_management;Username=admin;Password=password;
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=10
    depends_on:
      - db
    networks:
      - hotel_net
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hotel_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - hotel_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hotel_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d hotel_management"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  hotel_net:
    driver: bridge

volumes:
  hotel_data: